services:
  martin:
    image: ghcr.io/maplibre/martin
    restart: unless-stopped
    environment:
      - USER
    volumes:
      - ./osm:/data:z
      - /var/run/postgresql:/var/run/postgresql:z
    ports:
      - 3000:3000
    entrypoint: ["/bin/sh"]
    command: ["/data/martin/entrypoint.sh"]
    networks:
      - mvts-net

networks:
  mvts-net:
    driver: bridge